### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [mmilano/sketch-rotate-artboards#2]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by mmilano** [comment]
Resolved with the 1.0.2 release. 

After some time spent attempting to penetrate the unclear and full-of-black-holes documentation for the updating system details, it now appears to work.

note: pub date apparently needs to be in the past, not the future, for the download to work.

**Comment by bomberstudios** [comment]
> unclear and full-of-black-holes documentation

Could you please elaborate? I'd love to fix the docs to make them clearer!

**Comment by mmilano** [comment]
i'll have to think about that.
which side of the docs are you concerned with: the sketch side, or the sparkle side?

**Comment by mmilano** [comment]
note: i did add one comment to the discussion thread on this (http://sketchplugins.com/d/229-updating-plugins) which mentions only one point.

**Comment by mmilano** [comment]
also, out of curiosity, have you yourself tried making a plugin and making it work with updates? 
if not, feel free to consider the idea of checking out a simple plugin (you can take v1.0.1 of mine, for example) and implementing the update.
